version: "3.7"

services:
  django_project_postgres:
    container_name: django_project_postgres
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5002:5432"
    env_file:
      - .env
    restart: always

  django_project:
    container_name: django_project
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    stdin_open: true
    tty: true
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - django_project_postgres
    restart: always

volumes:
  postgres_data:

networks:
  default:
    external: false
    name: label_hub_bridge